# CPU-only development with PyTorch and Whisper
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    container_name: cloud_transcript_cpu
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src:ro
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./exports:/app/exports
      - ./cache:/app/cache
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_WATCH_FOR_CHANGES=true
      - USE_LOCAL_GPU=false
      - TRANSCRIPTION_MODE=cpu_whisper
      - WHISPER_DEVICE=cpu
    env_file:
      - .env
    networks:
      - cloud_transcript_network
    restart: unless-stopped

networks:
  cloud_transcript_network:
    driver: bridge